# Generated by Django 3.0.8 on 2020-07-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
