# Generated by Django 3.0.8 on 2020-09-25 04:10

import core.datatypes
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200828_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=core.datatypes.NullableForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_address', to='core.UserAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=core.datatypes.NullableDecimal(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=core.datatypes.NullableForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address', to='core.UserAddress'),
        ),
    ]
