# Generated by Django 3.0.8 on 2020-07-24 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200724_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='num_items_per_order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
