# Generated by Django 3.0.8 on 2020-07-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200723_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'verbose_name_plural': 'Item Variants'},
        ),
        migrations.AlterModelTable(
            name='itemvariant',
            table='item_variant',
        ),
    ]
