# Generated by Django 3.0.8 on 2020-07-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200724_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariant',
            old_name='num_items_per_order',
            new_name='quantity',
        ),
    ]
