# Generated by Django 3.0.8 on 2020-07-23 04:58

import core.datatypes
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200723_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='per_item_price',
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='num_items_per_order',
            field=core.datatypes.NullablePositiveInteger(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
