# Generated by Django 3.0.8 on 2020-07-23 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200723_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='max_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterModelTable(
            name='itemvariant',
            table='core_item_variant',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='core_order_item',
        ),
    ]
