from core.serializers.auth import RegistrationSerializer
from core.serializers.order import OrderSerializer
from core.serializers.product import ProductSerializer
from core.serializers.product_image import ProductImageSerializer
from core.serializers.rating_breakdown import RatingBreakdownSerializer
from core.serializers.user import UserSerializer